### ISSUE TITLE
Sandbox Profile Dump

### ISSUE THREAD

**Issue by V3rochka** [alephsecurity/xnu-qemu-arm64#11]
Decode and analyze sandbox profiles for iOS 12.1.

**Comment by dukebarman** [comment]
iPhone6, iOS 12.1: [iphone6_profiles.zip](https://github.com/alephsecurity/xnu-qemu-arm64/files/4275830/iphone6_profiles.zip)

I've used sandblaster port to python3 for this so if you find errors, say me plz.

**Comment by V3rochka** [comment]
Thanks @dukebarman , closing the issue :)
