### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by cutecodee** [alephsecurity/xnu-qemu-arm64#16]
I cloned the repo using 'git clone https://github.com/alephsecurity/xnu-qemu-arm64' as 'git clone git@github:alephsecurity/xnu-qemu-arm64' doesn't work for me, but qemu gives a lot of errors and doesn't compile:

fatal error: too many errors emitted, stopping now [-ferror-limit=]
220 warnings generated.
36 warnings and 20 errors generated.
make: *** [disas/libvixl/vixl/a64/disasm-a64.o] Error 1
220 warnings generated.
220 warnings generated.
220 warnings generated.
220 warnings generated.
220 warnings generated.
220 warnings generated.
214 warnings and 20 errors generated.
make: *** [disas/libvixl/vixl/a64/decoder-a64.o] Error 1
214 warnings and 20 errors generated.
make: *** [disas/libvixl/vixl/a64/instructions-a64.o] Error 1
220 warnings generated.
220 warnings generated.
223 warnings and 20 errors generated.
220 warnings generated.
make: *** [disas/arm-a64.o] Error 1

**Comment by V3rochka** [comment]
Hi @cutecodee 
Did you configure the project before the build?
```
./configure --target-list=aarch64-softmmu --disable-capstone --disable-pie --disable-slirp
```

**Comment by cutecodee** [comment]
yes i did and i haven't got any error

**Comment by cutecodee** [comment]
I'm using High Sierra, could it be a problem?

**Comment by V3rochka** [comment]
I guess it might, I am working with Catalina ... Do you have an option to run it on Catalina?

**Comment by cutecodee** [comment]
unfortunately I can't cause I've a very old hardware

**Comment by cutecodee** [comment]
https://pastebin.com/TxRi3Rx9 this is a part of the log, and all error are like these

**Comment by cutecodee** [comment]
could you try to upload the compiled version, so I can see if I can run it?

**Comment by jonyafek** [comment]
It is hard to understand from the errors exactly what the issue is. It seems like a general QEMU compilation issue. Please see if you can compile the regular QEMU project (not the XNU enabled one), and should work the same. https://wiki.qemu.org/Hosts/Mac

**Comment by cutecodee** [comment]
I've got it compiled and I prepared files two times but qemu gives "Abort trap: 6" error: 
![Schermata 2020-04-09 alle 15 50 19](https://user-images.githubusercontent.com/41830087/78902550-3a3e9480-7a7a-11ea-838a-734026313b64.png). This is the compile log 
[xnuqemu.log](https://github.com/alephsecurity/xnu-qemu-arm64/files/4456511/xnuqemu.log)

**Comment by V3rochka** [comment]
Great :) Closing the issue
