### ISSUE TITLE
Bash Script to emulate

### ISSUE THREAD

**Issue by brianherman** [alephsecurity/xnu-qemu-arm64#18]
Can I create a bash script on debian or ubuntu to emulate the feel of this repo?
https://github.com/foxlet/macOS-Simple-KVM

**Comment by V3rochka** [comment]
Hi @brianherman, I am not sure that I understand the question. Can you elaborate?

**Comment by sickcodes** [comment]
> Can I create a bash script on debian or ubuntu to emulate the feel of this repo?
> https://github.com/foxlet/macOS-Simple-KVM

Working on a Docker version

**Comment by brianherman** [comment]
oh cool if you are making adocker version that would be epyc.

**Comment by sickcodes** [comment]
MCApollo got it working on linux! Will get the auto build up soon

**Comment by sickcodes** [comment]
@brianherman  https://github.com/sickcodes/Docker-eyeOS automated script ready!
