### ISSUE TITLE
Add ability to execute code arbitrary kernel code on the guest machine without patching the kernel

### ISSUE THREAD

**Issue by jonyafek** [alephsecurity/xnu-qemu-arm64#2]
### Description

We want to have a simple framework to compile and execute arbitrary kernel code on the guest iOS machine. We want to have this without patching the kernel using a gdb script that will create fake task ports for our process. This will enable us to send messages to the kernel task port and therefore execute arbitrary kernel memory.

Compilation should be performed easily with a symbols file as input to link the function calls and global variables to their relevant locations.

**Comment by V3rochka** [comment]
Implemented by @jonyafek . Kernel was patched.
