### ISSUE TITLE
qemu-system-aarch64: Property '.tc-filename' not found

### ISSUE THREAD

**Issue by benquike** [alephsecurity/xnu-qemu-arm64#24]
Hi:

I am using this qemu to run ios following the guidelines shown here:https://alephsecurity.com/2019/06/17/xnu-qemu-arm64-1/

But I got the the following error messages: 

```
qemu-system-aarch64: Property '.tc-filename' not found
```

I have went through the log messages, it seems that in this commit 61226e8eeaece8620a305ab31747fbde697a2c05
tc-filename has been removed because trust cache is no longer needed because a patched kernel is used instead.

But the guideline in the link about does not show how to patch the kernel so that trust cache is not needed.
Can you please tell me how to do that?

Thanks!

**Comment by V3rochka** [comment]
Hi @benquike ,
The kernel is patched already within the repository's code, If you're interested, you can see all the patches [here](https://github.com/alephsecurity/xnu-qemu-arm64/blob/master/hw/arm/n66_iphone6splus.c).

The up-to-date guidelines to build the iOS on QEMU are kept in the [wiki ](https://github.com/alephsecurity/xnu-qemu-arm64/wiki/Build-iOS-on-QEMU) of this repository (as stated at the first paragraph of the blog post you had referred to  :slightly_smiling_face: )

Please follow the wiki's guideline and let us know if you have any issues with it  🙂

**Comment by benquike** [comment]
Thanks. It worked
