### ISSUE TITLE
Compiling for Windows (x64)?

### ISSUE THREAD

**Issue by y2k04** [alephsecurity/xnu-qemu-arm64#32]
Hi,

How would I compile this project for Windows? I keep getting compilation errors when I cross-compile in Windows Subsystem for Linux (Ubuntu 20.04).

Thanks,
Y2K4

**Comment by raspiduino** [comment]
Can you give the error log here, so people can look at it? Thanks!

**Comment by y2k04** [comment]
I was unable to retrieve the logs. Sorry!

**Comment by michelbarnich** [comment]
> I was unable to retrieve the logs. Sorry!

Well without logs, figuring out what went wrong is pretty much impossible.

**Comment by y2k04** [comment]
yeah… how would I compile it for Windows anyway?

**Comment by michelbarnich** [comment]
Its easier to compile it under WSL2

**Comment by y2k04** [comment]
That's what I was doing. I was compiling using Arch Linux (to use `pacman`) on WSL2.
