### ISSUE TITLE
Errors in rsync operations

### ISSUE THREAD

**Issue by dukebarman** [alephsecurity/xnu-qemu-arm64#6]
Try to reproduce a new Readme instructions (The old works :) )

```
 # sudo rsync -av /Volumes/PeaceB16B92.N56N66OS/.* /Volumes/PeaceB16B92.arm64UpdateRamDisk/
building file list ... done
.Trashes
.file
.HFS+ Private Directory Data\#015/
rsync: recv_generator: mkdir "/Volumes/PeaceB16B92.arm64UpdateRamDisk/.HFS+ Private Directory Data\#015" failed: No such file or directory (2)
.ba/
.mb/

sent 263 bytes  received 82 bytes  690.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-54/rsync/main.c(996) [sender=2.6.9]
```

Is it okay?

**Comment by V3rochka** [comment]
Hi @dukebarman ,
Thank you for reporting!!!
Please ignore syncing the hidden files for now. It will work without it. 
I will check the issue (will remove from readme for now)

Please let us know if you have any issue other with the installation :)

**Comment by V3rochka** [comment]
I am closing this issue.
Running `sudo diskutil enableownership /Volumes/PeaceB16B92.arm64UpdateRamDisk/` before the `rsync` command will fix the problem.
